#!/bin/bash

read -p "Insert m: " m
declare -A matrix
sum=0
num=0
var=0
for ((i=0;i<$m;i++)); do
	for ((j=0;j<$m;j++)); do
		matrix[$i,$j]=$(($i+$j))
		let var=${matrix[$i,$j]}
		if [[ $var%5 -eq 0 && $j<$i ]]; then
			sum=$(($sum+$var))
			num=$(($num+1))
		fi
        echo -n "${matrix[$i,$j]} "
	done
    echo
done
fsyo=$(($sum/$num))
echo " ______________ "
echo
echo $fsyo
