#!/bin/bash

read -p "Insert m: " m
declare -A matrix
var=0
for ((i=0;i<$m;i++)); do
	for ((j=0;j<$m;j++)); do
	matrix[$i,$j]=$i+$j
	let var=${matrix[$i,$j]}
	echo -n "$var "
	if [[ $var%2 -eq 0 && $(($i+$j))<$(($m-1)) ]]; then
					sum=$(($sum + $var))
	fi
    done
	echo
done
echo " ____________ "
echo
echo $sum
