#!/bin/bash

declare -A matrix

read -p "Insert m: " m
num=0
 for ((i=0;i<$m;i++)) do
    for ((j=0;j<$m;j++)) do
    matrix[$i,$j]=$i+$j
    let var=${matrix[$i,$j]}
    echo -n "$var  "
    if [[ $var -eq 0 && $(($i+$j))<$m ]]; then
	    num=$(($num+1))
     fi
     done
         echo
done

echo $num

