#!/bin/bash

#$1 is directory name $2 is file name

function arg 
{
    for i in $path
    do

	if [[ -f $i ]]
	then
		for (( x = ${#i}; x >= 0; x-- ))
		do
			if [[ ${i:$x:1} == / ]]
			then
				startPoint=$(($x+1))
			        endPoint=${#i}-$x
				tmp=${i:$startPoint:$endPoint}
				
				if [[ "$file" == "$tmp" ]]
				then
					echo $i
				fi
			fi
			done
	fi
	    
	if [[ -d $i ]]
	then
		path=$i/*
		arg
	fi
    done
}

function main
{
    path=$1/*
    file=$2
    
    arg
}

main $1 $2
