#!/bin/bash
sum=0
count=0
array=($@)
  for i in ${array[@]}
     do
             if [[ $i -lt 0 ]]
         then
          sqr=$(($i*$i))
          sum=$(($sum+$i))
	  count=$(($count+1))
          total=$(bc<<<"scale=1;$sum/$count") 
       fi

     done
     echo "e( l($total)/2 )" | bc -l







