#!/bin/bash
sum=0
count=0
array=($@)
  for i in ${array[@]}
     do
             
        if [[ $i -lt 0 ]]
         then
          sum=$(($sum+$i))
          count=$(($count+1))
          total=$(bc<<<"scale=3;$sum/$count")
       fi

     done
       echo "$total"

