#!/bin/bash
count=0
array=($@)
  for i in ${!array[@]}
    do
	    if ! [[ $i =~ ^[[:digit:]]+$ ]]
              then
                 echo "type numbers"
                 exit
            fi

      if [[ $i%$1 -eq 0 ]]
       then 
          count=$(($count + 1))
      fi 
  done 
echo "$count"
