#!/bin/bash

function 155
{
sum=0
for (( i = 10 ;i <=100 ; i++ ))
do
        if [[ $i%3 -eq 0 ]]
        then
                sum=$(($sum+$i))
        fi
done
b=$(($sum+$1))
echo $b
}

function 156

{

sum=0
for (( i = 10 ;i <=100 ; i++ ))
do
        if [[ $i%3 -eq 0 && $i%5 -eq 0  ]]
        then
                sum=$(($sum+$i))
        fi
done
b=$(($sum+$1))
echo $b

}

function 157

{
sum=0
for (( i = 100 ;i <=1000 ; i++ ))
do
        if [[ $i%5 -ne 0  ]]
        then
                sum=$(($sum+$i))
        fi
done
b=$(($sum+$1))
echo $b

}

function 158

{
sum=1
for (( i = 100 ;i <=1000 ; i++ ))
do
        if [[ $i%2 -ne 0 && $i%3 -ne 0 ]]
        then
                sum=$(($sum*$i))
        fi
done
b=$(($sum*$1))
echo $b
}

function 159
{
sum=1
for (( i = 100 ;i <= 1000 ; i++ ))
do
        if [[ $i%4 -eq 2 && $i%3 -eq 1 ]]
        then
                sum=$(($sum*$i))
        fi
done
b=$(($sum*$1))
echo $b
}


function 160
{
for (( i=100; i<1000; i++))
    do
      sum=$(($i*16))
      for (( k=1; k<$(($i/2)); k++ ))
         do
           if [[ $(($k*$k)) -eq  $sum ]] ; then
		      echo $i
		      exit
	    fi	   
    done
done
}


function 161

{
for (( i=1000; i<10000; i++))
    do
      sum=$(($i*26))
      for (( k=1; k<$(($i/2)); k++ ))
         do
	    if [[ $(($k*$k)) -eq  $sum ]] ;  then
		      echo $i
		      exit
	    fi	   
    done
done
}

function 162

{
for (( i=9999; i>999; i--))
    do
      sum=$(($i*14))
      for (( k=1; k<$i; k++ ))
         do
	    if [[ $(($k*$k)) -eq  $sum ]] ;  then
		    echo $i
		    exit 
	    fi	   
    done
done
}

function 163

{
for (( i>999; i=9999; i--))
    do
      sum=$(($i*18))
      for (( k=1; k<$i; k++ ))
         do
	    if [[ $(($k*$k)) -eq  $sum ]]
              then
		    echo $i
		    exit		   
	    fi	   
    done
done
}

function 164

{
for (( i=100; i<1000; i++))
    do
      for (( k=1; k<$(($i/2)); k++ ))
         do
		 if [[ $(($k*$k)) -eq $i && $k -gt $1 ]]
                  then
		      echo $i
		      exit
	    fi
    done
done
}
