#!/bin/bash
echo "enter the first number"
read x
echo "enter the second number"
read y
echo "enter action symbol"
read act

	if [[ ${x} =~ ^[[:digit:]]+$ && ${y} =~ ^[[:digit:]]+$ ]];then
		case $act in
	"+") echo "$x + $y =" $(expr $y + $x);;
	"-") echo "$x - $y =" $(expr $y - $x);;
	"/") if [ $y -eq 0 ] 
	then
		echo "eror : delimiter by zero";
	else 
		echo "$x / $y = " $(expr $x / $y);
	fi;;
	"*") echo " $x * $y =" $(expr $x \* $y);;

esac
fi;



