#!/bin/bash

my_find()
{
	for i in $1/*
	do
		if [[ -f $i ]]
		then
			echo $i
		else
			echo $i
			my_find $i
		fi
	done
}
my_find $1

#Command type without naming the file
#I will try to write the other way 

