#!/bin/bash
:'task32'
echo "Enter Size(N)"
read N

i=1
max=0

echo "Enter Numbers"
while [ $i -le $N ]
do
  read num
  if [ $i -eq 1 ]  
  then
      min=$num
  else             
      if [ $num -lt $min ]
      then
        min=$num
      fi
  fi
  i=$((i + 1))  
done

echo $min

