#!/bin/bash
declare -A arr
s=0
n=0
var=0
for ((i=0 ; i<$1; i++));do
        for ((j=0; j<$1 ; j++));do
                arr[$i,$j]=$(($i+$j))
                var=${arr[$i,$j]}
                if [[ $var%2 -eq 0 && $j<=$i ]];then
                        s=$(($s+$var))
                        n=$(($n+1))
                fi
                echo -n ${arr[$i,$j]}
        done
        echo
done
y=$(($s/$n))
echo $y


