#!/bin/bash

: 'Option 1

if [[ $(($1 % 2)) == 0 ]]; then
	echo "1"
elif [[ $(($2 % 2)) == 0 ]]; then
	echo "1"
elif [[ $(($3 % 2)) == 0 ]]; then
        echo "1"
else	
	echo "2"
fi'

: 'Option 2
if [[ $(($1 % 2)) == 0 || $(($2 % 2)) == 0 || $(($3 % 2)) == 0 ]]; then
       echo "1"
else
       echo "2"
fi'       
