#!/bin/bash

#$1=a $2=b $3=c

list=($1 $2 $3)

if [[ $1 -lt $2 && $1 -lt $3 ]]
then
	echo "Smaller is $1"
elif [[ $2 -lt $3 && $2 -lt $1 ]]
then
	echo "Smaller is $2"
else [[ $3 -lt $1 && $3 -lt $2 ]]

	echo "Smaller is $3"
fi
