#!/bin/bash
read -p "enter the string  " str
read -p "enter the substring  " sub
if [[ -n $str && -n $sub ]]; then
        res=`echo $str | grep "$sub"`
        
        if [[ -n $res ]]; then
                echo "true"
        else
                echo "false"
        fi
fi
