#!/usr/bin/python


print("For exiting print 'c'")
number = 0

while True:
    num = input("Enter number : ")
    
    if num == "c":
        break
    
    if num.isdigit():
        num = int(num)
        if num % 2 == 0:
            number += 1
            print(number)
