#!bin/bash

list=( 5 2 12 3 8 4 )
res=1
sum=0
for i in ${list[@]}; do
    if [[ $i%2 -eq 0 ]]; then
        res=$(($res*$i))
	sum=$(($sum+$i))
    fi
done
echo "List is: " ${list[@]}
echo "Sum: $sum" "Mult: $res"
