#!/bin/bash

list=( 5 0 12 0 8 0 )
sum=0
count=0
res=0
for i in ${list[@]}; do
    if [[ $i -eq 0 ]]; then
        count=$(($count+1))
    fi
done
echo "List is " ${list[@]}
echo "Result is: " $count

