#!/bin/bash


read -p 'input math expression (only two numbers): ' exp

list=()

#action detect
a=""

function action
{
	if [[ $a == "+" ]]
	then
		let answer=${list[0]}+${list[1]}
		echo "Answer: $answer"
	elif [[ $a == "-" ]]
	then
		let answer=${list[0]}-${list[1]}
		echo "Answer: $answer"
	elif [[ $a == "*" ]]
	then
		let answer=${list[0]}*${list[1]}
		echo "Answer: $answer"
	elif [[ $a == "/" ]]
	then
		let answer=${list[0]}/${list[1]}
		echo "Answer: $answer"
	fi
}
#counts action symbols for exceptions
count=0

function main 
{
	for (( i = 0; i <= ${#exp}; i++ ))
	do
		if [[ ${exp:$i:1} == "+" || ${exp:$i:1} == "-" || ${exp:$i:1} == "/" || ${exp:$i:1} == "*" ]]
		then
			let count=$count+1
		fi
	done
	
	if [[ $count -gt 1 ]]
	then
		echo "False expression"
		exit 127
	else
		cutter
		action
	fi
}

function cutter
{
	for (( i = 0; i <= ${#exp}; i++ ))
	do
		if [[ ${exp:$i:1} == "+" ]]
		then
			a="+"
			
			let startPoint=$i+1
			let endPoint=${#exp}-$startPoint
			list[0]=${exp:0:$i}
			list[1]=${exp:$startPoint:$endPoint}
			
			break
		elif [[ ${exp:$i:1} == "-" ]]
		then
			a="-"

                        let startPoint=$i+1
                        let endPoint=${#exp}-$startPoint
                        list[0]=${exp:0:$i}
                        list[1]=${exp:$startPoint:$endPoint}

                        break
		elif [[ ${exp:$i:1} == "/" ]]
                then
                        a="/"

                        let startPoint=$i+1
                        let endPoint=${#exp}-$startPoint
                        list[0]=${exp:0:$i}
                        list[1]=${exp:$startPoint:$endPoint}

                        break
		elif [[ ${exp:$i:1} == "*" ]]
                then
                        a="*"

                        let startPoint=$i+1
                        let endPoint=${#exp}-$startPoint
                        list[0]=${exp:0:$i}
                        list[1]=${exp:$startPoint:$endPoint}

                        break
		fi
	done	
}

main
