#!/bin/bash

  a=15     #a=$a
  b=3      #b=$b
  c=55     #c=$c 
  if    [[ $a < $b && $a < $b ]]; then
       echo "$a"
  elif  [[ $b < $a && $b < $c ]]; then
       echo "$b"
  else 
       echo "$c"
  fi

