#!/bin/bash

function hw_151
{
    n=0
    for (( i=1; i <= $1/2; i++ )); do
        if [[ $1%i -eq 0 ]]; then
            n=$(($n+$i))
        fi
    done
    echo $n
}

function hw_152
{
    n=1
    for (( i=1; i <= $1/2; i++ )); do
        if [[ $1%i -eq 0 ]]; then
            n=$(($n*$i))
        fi
    done
    echo $n
}

function hw_153
{
    n=0
    for (( i=1; i <= $1/2; i++ )); do
        if [[ $1%i -eq 2 ]]; then
            n=$(($n+$i))
        fi
    done
    echo $n
}

function hw_154
{
    n=1
    for (( i=1; i <= $1/2; i++ )); do
        if [[ $1%i -eq 3 ]]; then
            n=$(($n*$i))
	fi
    done
    echo $n
}

function hw_155
{
    n=0
    for (( i=10; i <= 99; i++)); do
        if [[ $i%3 -eq 0 ]];then
        n=$(($n+$i))
	fi
    done
    echo $n
}

function hw_156
{
    n=1
    for (( i=10; i <= 99; i++ )); do
        if [[ $i%3 -eq 0 && $i%5 -eq 0 ]]; then
	    n=$(($n*$i))
	fi
    done
    echo $n
}

function hw_157
{
    n=0
    for (( i=100; i <= 999; i++ )); do
        if [[ $i%5 -ne 0 ]]; then 
	    n=$(($n+$i))
	fi
    done
    echo $n
}

function hw_158
{
    n=1
    for (( i=100; i <= 999; i++ ));do
        if [[ $i%2 -ne 0 && $i%3 -ne 0 ]]; then
            n=$(($n*$i))
        fi
    done
    echo $n
}

function hw_159
{
    n=1
    for (( i=100; i <= 999; i++ )); do
        if [[ $i%3 -eq 1 && $i%4 -eq 2 ]]; then
	    n=$(($n*$i))
	fi
    done
    echo $n
}

function hw_168
{
    n=$1
    if [[ $n -gt 1 ]]; then
       for ((i=2; i<=$(($n-1)); i++)); do
           if [[ $n%$i -eq 0 ]];then
               p=false
	       break
           else
               p=true
           fi
       done
       echo $p
    fi
}
