#!/bin/bash

arr=(5 65 0 -78 58 -5 -21 36)
b=1
for i in ${!arr[@]}; do
    if [[ $i%2 -ne 0 && $i -ne 0 ]];then
	    a=$((${arr[i]}*${arr[i]})) 
	    b=$(($b*$a))
    fi
done
echo "The product of squares: $b"
