#!/bin/bash

arr=(5 65 0 -78 58 0 -5 -21 36)
max=arr[0];
min=arr[0];
for i in ${arr[@]};do 
	if [[ $i -gt $max ]]; then
		max=$i
	elif [[ $i -lt $min ]]; then
		min=$i
	fi
done
a=$(($max + $min))
echo "The sum of the biggest and smallest elements: $a"
