#!/bin/bash
arr=(5 20 14 7 62 3)
max=0
min=${arr[0]}

for i in ${arr[@]}
do
        if (( $i > $max )); then
                max=$i
        fi

        if (( $i < $min )); then
                min=$i
        fi
done

echo $(($max + $min))
