#!/bin/bash
declare -A arr
array=($@)

sqNum=0

arr=()

sqrRoot="$(bc <<<"scale=3; sqrt(${#array[@]})")"
size=0

for (( i = 0; i <= ${#sqrRoot}; i++ ))
do
	if [[ ${sqrRoot:$i:1} == "." ]]
	then
		startP=$(($i+1))
		endP=$((${#sqrRoot}-$i))
		
		str=${sqrRoot:$startP:$endP}

		if [[ ! $str == 000 ]]
		then
			echo "Count of arguments should be square of some number"
			echo "Example: Count arguments is 25 which is square of 5"
			exit 2
		else
			size=${sqrRoot:0:$i}
		fi
	fi
done

for (( x = 0; x < $size; x++ ))
do
    for (( y = 0; y < $size; y++ ))
    do
	arr[$x,$y]=${array[$sqNum]}
	sqNum=$(($sqNum+1))
    done
done

sum=0
sqr=1

#i iterates count of members on angle
i=1

#count of members that divide on given K num
count=0

for (( x = 0; x < $size; x++ ))
do
    for (( y = 0; y < $i; y++ ))
    do
	if [[ ${arr[$x,$y]}%2 -eq 0 && ${arr[$x,$y]} -ne 0 ]]
	then
	    sqr=$((${arr[$x,$y]}*${arr[$x,$y]}))
	    sum=$(($sqr+$sum))
	    count=$(($count+1))
	fi
    done
    i=$(($i+1))
done

if [[ ! $count -eq 0 ]]
then
    divide=$(($sum/$count))
    avg=$(bc <<<"sqrt($divide)")
else
    echo "Can not divide on 0"
    exit 3
fi

echo $avg




