#!/bin/bash
declare -A arr
array=($@)

sqNum=0

arr=()

sqrRoot="$(bc <<<"scale=3; sqrt(${#array[@]})")"
size=0

for (( i = 0; i <= ${#sqrRoot}; i++ ))
do
	if [[ ${sqrRoot:$i:1} == "." ]]
	then
		startP=$(($i+1))
		endP=$((${#sqrRoot}-$i))
		
		str=${sqrRoot:$startP:$endP}

		if [[ ! $str == 000 ]]
		then
			echo "Count of arguments should be square of some number"
			echo "Example: Count arguments is 25 which is square of 5"
			exit 2
		else
			size=${sqrRoot:0:$i}
		fi
	fi
done

for (( x = 0; x < $size; x++ ))
do
    for (( y = 0; y < $size; y++ ))
    do
	arr[$x,$y]=${array[$sqNum]}
	sqNum=$(($sqNum+1))
    done
done

#Array for all numbers that divide on 5
sum=0

#i iterates count of members on angle
i=1

#count of members that divide on given K num
count=0

for (( x = 0; x < $size; x++ ))
do
    for (( y = 0; y < $i; y++ ))
    do
	if [[ ${arr[$x,$y]}%5 -eq 0 && ${arr[$x,$y]} -ne 0 ]]
	then
            sum=$((${arr[$x,$y]}+$sum))
	    count=$(($count+1))
	fi
    done
    i=$(($i+1))
done

avg=$(($sum/$count))

echo $avg




