#!/bin/bash

if [[ $1 =~ ^[0-9]+$ && $3 =~ ^[0-9]+$ ]]
  then
    case $2 in
      '+') echo $(( $1 + $3 ));;
      '-') echo $(( $1 - $3 ));;
      '*') echo $(( $1 * $3 ));;
      '/') echo $(( $1 / $3 ));;
    esac
else
       	echo "Enter numbers."
fi

#write during multiplication \*

