#!/bin/bash
array=($@) 
max=${array[0]}
for i in ${array[@]}
do
	if ! [[ $i =~ ^[[:digit:]]+$ ]]
	 then
		 echo "type numbers"
		 exit
	fi
	 if [[ $i -ge $max ]]
	  then
		  max=$i
	fi
done
echo $max
