#!/bin/bash
array=($@)
min=${array[0]}
for i in ${array[@]}
do
        if ! [[ $i == ?(-)+([0-9]) ]]
           then	
	     echo "Not a number"	   
		exit 0
	fi     	
         if [[ $i -lt  $max ]]
          then
                  min=$i
        fi
done
echo   "min= $min"
              
