#!/bin/bash
array=($@)
min=${array[0]}
for i in ${array[@]}
do
        if ! [[ $i =~ ^[[:digit:]]+$ ]]
         then
                 echo "type numbers"
                 exit
        fi
         if [[ $i -lt  $max ]]
          then
                  min=$i
        fi
done
echo   "min= $min"
              
