#!/usr/bin/python3
num1 = int(input("enter the first number: "))
num2 = int(input("enter the second number: "))
st = 0
end = 0
if num2 > num1:
    st = num1
    end = num2
else:
    st = num2
    end = num1

for i in range(st, end, 1 ):
    if i % 15 == 0:
        print("FizzBuzz", i)
    elif i % 3 == 0:
        print("Fizz", i)
    elif i % 5 == 0:
        print("Buzz", i)

