#!/bin/bash

arr=(2 8 14 20 26 32);

isProgression=true

for (( i = 0 ; i < ${#arr[@]}; i++ )); do 

   if [[ -n ${arr[$i + 2]} ]]; then 
        if [[ $(( ${arr[$i]} - ${arr[$i+1]} )) -ne $(( ${arr[$i+1]} - ${arr[$i+2]} )) ]]; then
             isProgression=false;
             break; 
        fi
	       
   elif [[ -n ${arr[$i + 1]} ]]; then
        if [[ $(( ${arr[$i-1]} - ${arr[$i]} )) -ne $(( ${arr[$i]} - ${arr[$i+1]} )) ]]; then 
             isProgression=false;
             break;
        fi
   fi 
done

if [[ $isProgression == true ]]; then 
        echo "Progressia e "
else 
        echo "Progressia che "
fi
    



