#!/bin/bash

my_find()
{
	for i in $1/*
	do
		if [[ -f $i && $i == $1/$2 ]]
		  then
			echo $1/$2
			exit
		elif [[ -d $i ]]
		  then
			last=${i##*,}
                        for j in $last/*
	                   do 
			     if [[ -f $j && $j == $last/$2 ]]
			        then
			          echo $i/$2
			     elif [[ -d $j ]]
			       then
			        my_find $i $2
			    fi
		       done
		  
		fi	
	done
}
my_find $1 $2
 
