#!/bin/bash
sum=0
count=0
array=($@)
  for i in ${array[@]}
do
	if ! [[ $i == ?(-)+([0-9]) ]]
           then	
	     echo "Not a number"	   
		exit 0
	fi     	
                if [[ $i -gt 0 ]]
                   then
          sum=$(($sum+$i))
          count=$(($count+1))
          total=$(bc<<<"scale=3;$sum/$count")
                fi
	     
     done
       echo "$total"
                     
