#!/bin/bash

array=($@)
mul=1
for i in ${!array[@]}
  do
          if ! [[ $i == ?(-)+([0-9]) ]]
           then
             echo "Not a number"           
                exit 0
         fi     

    if [[ $i%2 -eq 0 && $i -ne 0 ]]
      then
        mul=$(($mul*${array[i]}))
    fi

 done
   echo $mul

                                                                                                                                    
          
