#!/bin/bash

array=($@)
sum=0
for i in ${array[@]}
   do 
          if ! [[ $i == ?(-)+([0-9]) ]]
           then	
	     echo "Not a number"	   
		exit 0
          fi     	     
    if [[ i%2 -eq 0 ]]
      then
        i=$(($i*$i))
        sum=$(($sum+$i))
    fi
   done
 echo "$sum"
