#!/bin/bash

array=($@)
count=0
for i in ${array[@]}
   do 
	 if ! [[ $i == ?(-)+([0-9]) ]]
           then	
	     echo "Not a number"	   
		exit 0
         fi     	
 
     if [[ i%2 -eq o ]]
      then
        count=$(($count+1))
     fi
   done
 echo "$count"
