#!/bin/bash

#$1=a $2=b $3=c

list=($1 $2 $3)

if [[ $1 -gt $2 && $1 -gt $3 ]]
then
	echo "Biggest is $1"
elif [[ $2 -gt $3 && $2 -gt $1 ]]
then
	echo "Biggest is $2"
else [[ $3 -gt $1 && $3 -gt $2 ]]

	echo "Biggest is $3"
fi
