#!/bin/bash

array=($@)
sum=0
for i in ${array[@]}
   do 
          if ! [[ $i =~ ^[[:digit:]]+$ ]]
              then
                 echo "type numbers"
           fi     
    if [[ i%2 -eq 0 ]]
      then
        i=$(($i*$i))
        sum=$(($sum+$i))
    fi
   done
 echo "$sum"
