#!/bin/bash

sum=0
mul=1
array=($@)
  for i in ${array[@]}
   do
	  if ! [[ $i == ?(-)+([0-9]) ]]
           then	
	     echo "Not a number"	   
		exit 0
	  fi     	

       if  [[ $i%2 -eq 0 ]]
          then
           sum=$(($sum+$i))
           mul=$(($mul*$i))
       fi
  done
   echo "mul=$mul
      sum=$sum "
