#!/bin/bash
count=0
mul=1
array=($@)
   for i in ${array[@]}
    do
	  if ! [[ $i == ?(-)+([0-9]) ]]
           then	
	     echo "Not a number"	   
		exit 0
	  fi     	

      if [[ i%2 -ne 0 ]]
       then 
        mul=$(($mul*$i))
         count=$(($count+1))
      fi
    done
echo "mul=$mul
      count=$count"
