#!/bin/bash
count=0
array=($@)
   for i in ${array[@]}
    do
	    if ! [[ $i == ?(-)+([0-9]) ]]
           then	
	     echo "Not a number"	   
		exit 0
            fi     	

     if [[ $i -eq 0 ]]
      then
       count=$(($count+1))
     fi
    done
echo "count=$count"
