#!/bin/bash

array=($@)

sqr=1
sum=0

for i in ${array[@]}
do
    if [[ $i =~ ^[-0-9]+$ ]]
    then
	if [[ $i%2 -eq 0 ]]
	then
		sqr=$(($i*$i))
		sum=$(($sqr+$sum))
	fi
    else
	echo "$i is not a number"
    fi

done

echo $sum
