#!/bin/bash

list=( 5 2 12 3 8 4 )
sum=0
count=0
res=0
for i in ${list[@]}; do
    if [[ $i%2 -ne 0 ]]; then
	sum=$(($sum+$i))
	count=$(($count+1))
    fi
done
res=$(($sum/$count))
echo "List is " ${list[@]}
echo "Result is: " $res
