#!/bin/bash

list=( 5 2 12 3 8 4 )
mult=1
count=0
for i in ${list[@]}; do
    if [[ $i%2 -ne 0 ]]; then
        mult=$(($mult*$i))
        count=$(($count+1))
    fi
done
echo "List is " ${list[@]}
echo "Count: $count" "Mult: $mult"

