#!/bin/bash

array=($@)

sum=0
count=0

for i in ${array[@]}
do
    if [[ $i =~ ^[-0-9]+$ ]]
    then
	    if [[ $i%2 -ne 0 ]]
	    then
		sum=$(($sum+$i))
		count=$(($count+1))
	    fi
    else
	    echo "$i is not a number"
    fi
done

avg=$(($sum/$count))

echo $avg
