#!/bin/bash

array=($@)

sqr=1
sum=1

for i in ${!array[@]}
do
    if [[ ${array[$i]} =~ ^[-0-9]+$ ]]
    then
	if [[ $i%2 -ne 0 ]]
	then
		sqr=$((${array[$i]}*${array[$i]}))
		sum=$(($sqr*$sum))
	fi
    else
	echo "${array[$i]} is not a number"
    fi
done

echo $sum
