#!/bin/bash

array=($@)

read -p 'K: ' num

count=0

for i in ${!array[@]}
do
    if [[ ${array[$i]} =~ ^[-0-9]+$ ]]
    then
	if [[ $i%$num -eq 0 && $i -ne 0 ]]
	then
		count=$(($count+1))
	fi
    else
	echo "${array[$i]} is not a number"
    fi
done

echo $count
