#!/bin/bash

array=($@)

sum=0

for i in ${!array[@]}
do
	if [[ ${array[$i]} =~ ^[-0-9]+$ ]]
	then
	    if [[ $i%2 -eq 0 && $i -ne 0 ]]
	    then
		    sum=$(($sum+${array[$i]}))
	    fi
 	else
	    echo "${array[$i]} is not a number"	
	fi
done

echo $sum
