#!/bin/bash

array=($@)

count=0

for i in ${array[@]}
do
    if [[ $i =~ ^[-0-9]+$ ]]
    then
        if [[ $i%2 -eq 0 ]]
        then
	    count=$(($count+1))
        fi
    else
	echo "$i is not a number"
    fi
done

echo $count
