#!/bin/bash

a=$1
b=$2
c=$3
if [[ $# -ne 3 ]]; then
    echo "You need to specified 3 arguments."
    exit 1
fi
if [[ $a -gt $b && $a -gt $c ]]; then
    echo  $a
elif [[ $b -gt $a && $b -gt $c ]]; then
    echo $b
else
    echo $c
fi
