#!/bin/bash

a=$1
b=$2
c=$3
if [[ $# -ne 3 ]]; then
    echo "You need to specified 3 arguments."
    exit 1
fi
if [[ $a -eq 2 && $b -eq 2 || $a -eq 2 && $c -eq 2 || $b -eq 2 && $c -eq 2 ]]; then
    echo "True"
else 
    echo "False"
fi
