#!/bin/bash

a=$1
b=$2
c=$3
if [[ $# -ne 3 ]]; then
    echo "Petq e mutqagreq 3 argument."
    exit 1
fi
if [[ $((a%2)) -eq 0 || $((b%2)) -eq 0 || $((c%2)) -eq 0 ]]; then
    echo "1"
else
    echo "2"
fi
